### ISSUE TITLE
[ Discussion ] Goals.

### ISSUE THREAD

**Issue by herronelou** [mapoga/nuke-vector-matrix#1]
Hey Mathieu.
Before we get started, what are the goals of the toolset?
Do we limit them to be extra technical nodes to be used as building blocks (ie. gizmo internals), or do we want to make them "user friendly" and spend a bit more time making them feel like full tools?
Or do we want to separate it into 2 categories, to have some that are user facing, and others purely meant to be building blocks?

**Comment by mapoga** [comment]
Hi Erwan.
I think that 2 categories would be best.
We could create a new directory beside the one named 'Math' which would be higher level and more user friendly. I already have some in my other repo named Tools/3D that we could transfer if it fits.

**Comment by herronelou** [comment]
I'm thinking maybe a minimum amount of wrapping though to make them feel like like an united set of tools, for example a picker for the vector layer for all the vector tools and a small copyright with a link to this github. Keeping it very minimal for the building blocks.
Looking at what you have in the repo right now, although your menu/init.py are useful they feel like they are very dedicated to the way you are creating your menus, and are not compatible with the method we have to create menu entries where I work for example.
As we're making a vector/matrix toolset, I feel like we should stop at that, providing a set of .nk or .gizmo files. 
Eventually we can make a top level init/menu.py to provide to whoever doesn't have their in-house gizmo managers, but one in each sub-directory is a bit much for me right now.

I also believe we should try to stick to "Good standards" (well, mostly avoiding the bad practices) as they are mentioned in there: https://gitlab.com/frueter/nuke-code-guide/issues/
And overall stick to following pep8 for any python code (though I am cool breaking naming conventions to follow nuke's camelCase function/variable names).

How do you want to work? Do you prefer I fork the project and we each work into a separate project with a separate set of issues or do you want to add me as a collaborator on this repo?

**Comment by mapoga** [comment]
I agree with everything you mentioned. Although i rushed the commit before
my flight. Right now you can just fork

**Comment by herronelou** [comment]
Cool, well, I'm pretty busy with a large piece of code I need to deliver for work which may take a few more weeks, so there is no rush, we can look into it when you get back.

**Comment by herronelou** [comment]
The worst is behind me, I think I'll have some time on saturday to start looking at this suite of tools. Would be good if you're around to have a chat that day to see where we want to bring this.

**Comment by mapoga** [comment]
Good to hear. I just sent you a collaboration invite. I should be available to chat next saturday around this time.

I spent the last days getting used to PEP8 as i never really knew those guidelines but now glad i do. I also have to spend some time reading the nuke-code-guide and get familiar with it. I removed all menu/init.py from the repo.

Here are some topics for discussion. I would like to have your opinion on them. At the end we could make a guideline if necessary.

**1. Naming conventions**
- Match nuke's naming by using the CapitalizedWords style.
- Trail with the category e.g. Determinant3x3. Useful as a namespace, but at the end for easier search. 3x3, M3, V3 or else...
- Have the group/gizmo's name the same as the .nk/.gizmo's filename? Or a shorter version of it? e.g. Determinant3x3 vs Det3x3
- Tab knob label same as node's name?
- Pipes names vector, vectorA, vectorB, matrix, matrixA, matrixB ?
- Pipe B always on the left as the main pipe.

**2. Toolset wrapping/uniformity**
- Default knobs/info to put on all the nodes.
- Simple copyright and link for building blocks.

**3. Objectives**
- Fill the Vector2 category
- Fill the Matrix3x3 category
- Make some useful nodes to work with vectors like: DistanceBetween, AngleBetween...
- Try and optimize slow nodes like the InvertMatrix4x4. Probably make it in BlinkScript if its faster.
- Have different levels of use for the nodes/functions: knob, whole image at once, per pixel. Right now everything is per pixel. Do not know the best way to implement yet. Maybe a single node with a pulldown choice between the 3 and a switch within the group?
- What user friendly tools to make?
  - 2D vectors/normals tools as you have.
  - St to vectors and vectors to st like you have.
  - Fake refraction/reflection with ior
  - Camera Angle of view vector mapping.
  - 3D normals convert from world to camera?
  - 3D normals facing a vector ramp.
  - ...

I would love to read your thoughts on these subjects.

**Comment by herronelou** [comment]
**1. Naming conventions**
- Match nuke's naming by using the CapitalizedWords style. **-- Agreed**
- Trail with the category e.g. Determinant3x3. Useful as a namespace, but at the end for easier search. 3x3, M3, V3 or else..**.-- agreed**
- Have the group/gizmo's name the same as the .nk/.gizmo's filename? Or a shorter version of it? e.g. Determinant3x3 vs Det3x3 **-- same**
- Tab knob label same as node's name? **-- I would say so, though maybe  simplified version of it, may not necessarily need the category at the end**
- Pipes names vector, vectorA, vectorB, matrix, matrixA, matrixB ? **-- yes**
- Pipe B always on the left as the main pipe. **-- definitely, this is a must**
**I would also give some thoughts on a name that wouldn't be too intrusive with other tools. I named mine initially Vectors_Something, and now in the tab menu it always shows when I search the built in vectorDistort, vectorfield, etc.. though a lot of these new vector tools from the foundry came in with smart vectors a few years after I had made my tools..
It seems like starting with the action and going to the category it affects might not clash too much with built in tools: RotateMatrix3, InverseMatrix4, ConvertST, ConvertVector2, etc..**

**2. Toolset wrapping/uniformity**
- Default knobs/info to put on all the nodes. **-- yes, we do need these**
- Simple copyright and link for building blocks. **-- yes, we do need these**

**3. Objectives**
- Fill the Vector2 category
- Fill the Matrix3x3 category
- Make some useful nodes to work with vectors like: DistanceBetween, AngleBetween...
- Try and optimize slow nodes like the InvertMatrix4x4. Probably make it in BlinkScript if its faster. **-- so far I have been unimpressed by blinkscript's performance, and reliability in production, but it is good for kernels that only access 1 pixel at the time.**
- Have different levels of use for the nodes/functions: knob, whole image at once, per pixel. Right now everything is per pixel. Do not know the best way to implement yet. Maybe a single node with a pulldown choice between the 3 and a switch within the group? **-- I was thinking about the same thing, though I was only thinking about per pixel or per knob. What do you mean by whole image?**
- What user friendly tools to make?
  - 2D vectors/normals tools as you have. **-- Yes, see further my proposed hierarchy**
  - St to vectors and vectors to st like you have.
  - Fake refraction/reflection with ior
  - Camera Angle of view vector mapping.
  - 3D normals convert from world to camera?
  - 3D normals facing a vector ramp.
  - ...

**More thoughts :** 
I feel like with all these tools, there is quite a bit of overlap and duplicated functions that may happen.
Let's say a RotateVec3 tool: It could be rotated by an angle (as a degrees/radians knob) or rotated per pixel by a degrees/radian image, or rotated by a 3*3 matrix knob, or per pixel by a 3x3 pixel matrix.
In this case, do we get granular for the utility nodes, and have 4 nodes one for each situation (= lighter scripts because lighter gizmos/groups) or do we make one node with options for different controls (less nodes to juggle, but heavier nodes as they need to contain all methods).
If these utilities are gizmos, it won't affect the final filesize of a script that would use hundreds of them at all, but if they are groups we're starting to bloat the script. I do like to keep the simpler utility nodes as group though to let people easily dive in and modify, which could counterbalance the issue of bloating the group: An advanced user would get in and just take the pieces they need maybe rather than use the whole thing?

For the categories of tools I was thinking:
```
vector_matrix/
    conversion/
        conversionTool1.nk/gizmo
        ....
    math
        matrix3/
            inverse_matrix3.nk
            ....
        matrix4/
        vector2/
        vector3/
        (matrix2 and vector4?)/

    FirstLevelTool.nk/gizmo
    OtherTool.nk

```

The idea would almost be that at the first level, we can provide some premade tools that make use of the tools in the math and conversion categories, which are our building blocks. These would almost be like SDK examples or API examples, showing examples of how the building blocks could be used.

**Comment by herronelou** [comment]
Additionally, thinking about gizmos vs groups, I would be tempted to have all building blocks as groups, and "pre-made" tools as gizmos.
I'm not even sure putting gizmos inside a gizmo is doable, but that sounds like a recipe for a disaster. 
I wish the foundry would fix their ability to set default values on knobs, that would make groups more usable as alternatives to gizmos.

**Comment by herronelou** [comment]
Also, I've added you on linkedin (only place I could find your contact info) in case we want to get in touch and do an actual conversation or something, though talking here in public might not be bad if some others maybe one day want to collaborate.

**Comment by mapoga** [comment]
Alright we seem to be thinking the same.

- As for the wraping/uniformity you seem to have a better idea of what it should be than i do so if you can suggest a template it would be useful.
- I did a little digging afterwards with BlinkScripts and found it slower than expressions on a lot of things so it might not be an option. I am saving this step for last anyway.
- The "whole image" in retrospect is the same as knob. So just knob and per pixel.
- I like the categories with toplevel tools/examples
- For the overlap/duplicated functions i feel like we should make granular(lighter) nodes for the building blocks with radians/degrees always as a pulldown choice where degrees are involved since the conversion is "light".
- I dont think matrices should be combined with individual "action" directly on vectors as they can carry multiple "actions". This may lead to unwanted behavior. For example a 3x3 rotation matrix on a vector3 have rotation but can have scale as well.
- I think as a guideline we should keep functions that work directly on vectors to: "vector(knob or per pixel) on vector" or "matrix(knob or pixel) on vector" but never combined. For functions on matrices: "vector(knob or pixel) on matrix" or "matrix(knob or pixel) on matrix" but never combined.
- I think we should make a clear tree/list of nodes we would like with their inputs and main controls to get a good start. Then we can elaborate on something more tangible. As a start i will create a new file for the nodes roadmap where we can edit what we would like to have.
- As for groups vs gizmos i agree that block could be groups and maybe we could offer both for the tools as its not always easy to get gizmos accepted in a company where a ton of tools are already used.

**Comment by herronelou** [comment]
Ok. 
I made a new branch with different naming conventions, you can take a look.
I'm thinking for the list of tools and stuff, we should start building a documentation. Have you worked with Sphinx or similar before? Or should we keep it simple and just have a few .md files so that it's readable in github?

**Comment by mapoga** [comment]
I have never worked with Sphinx but we can start simple with .md and if we need we can switch to Sphinx.

**Comment by herronelou** [comment]
Actually since we will have very little python, might be just as easy to use github's wiki + a changelog and a readme. I started setting this up.

**Comment by herronelou** [comment]
I have a work in progress for all the Vec2 and Vec3 tools. Somehow it seems like my Git key isn't valid anymore so I haven't been able to push to Github, and no time to investigate. Will try to get back to it at some point, but thing have been hectic over here.

**Comment by mapoga** [comment]
Great to hear for the tools. On my side i did some tests on how to present the interface but nothing major. Its in the Matrix4 branch. I got stuck on making a matrix4x4 knob and keeping the values on copy. For now i use the knobs of an axis node. Not as clean as i would like but it gets the job done.
I dont think i will have much time to work on it in the next few weeks but i will get back at it when i get more free time.
As for the Git key, i changed nothing and i still see you as a contributor. Tell me if i can help.

**Comment by herronelou** [comment]
Ok, solved my SSH key issue, pushed my stuff from last week.

**Comment by herronelou** [comment]
Hey Mathieu,
I pushed a bunch of stuff to the dev branch. Make sure you check it out before you resume your work.

I was wondering about your knob only matrix tools, are they really only affecting the knobs? We probably do want to affect the image always, don't we? Can't we use Axis nodes if we want to do a bunch of transforms on a single matrix?

**Comment by herronelou** [comment]
I have pushed a branch called `matrix_suggestion` where I have edited the matrix4.nk to show you how I was thinking of implementing the default matrix generator. Let me know what you think about it. I felt the other one was a bit overwhelming.

**Comment by mapoga** [comment]
Hi Erwan,
Glad to see at least of of us is making progress ;) I hope to find time soon enough to make my end of the deal. Btw if you find a good way to make matrix knobs without an axis node im really really interested to know about it.

I like what you did for the vector2-3. You even did a blinkscript for matrix3 and vector product. I'm interested to know if you got some speed increase by using BlinkScript. Anyway its much simpler and easier to read.

My toughs on making knobs only operations is that sometimes you want to affect knobs on others nodes and the axis node doesn't do everything like inverting a matrix. Ex: I recently made a parenting constraint node in nuke and i had to invert the matrix knob of an axis node. No pixels were used in that operation since its with 3d transforms directly. Since i had nothing to inverse the matrix with(aka our toolset), i half assed it by manually linking the inverse of trans, rot and scale knobs and not automatically considering the transform order nor the rotation order. A simple invert matrix knob would have done the job.

I agree with you that the nodes i made are overwhelming and could be stripped down.
IdentMatrix: Mine is for both knobs and image in mind but in retrospect i think a separate and simpler one for each is better. The one you did would be the image version of it.
KnobsOnly: Remove the redundant input matrix and keep only input knob and output.

**Comment by herronelou** [comment]
I got it, I guess it makes sense, but yeah, let's keep them separated. And I think it could be good to actually connect their input and output to Axii so that it can be used to manipulate Axii directly.

**Comment by mapoga** [comment]
Yes. It already works with axis and readgeo as input since it looks for the "world_matrix" knob on the connected input. I would love to make it work with axis connect to it downstream but im not sure what the axis expect and if its even possible at all.

**Comment by herronelou** [comment]
Hello,
I've merged all my changes + yours in dev, make sure you pull that in before resuming your work.
We should probably start being a bit cleaner with our git branches, making new branches from dev for specific features, etc...
I have put a node in the matrix4 knob only called InverseAxis, Which is how I was imagining the knob only nodes, having them usable as Axis directly. Take a look and let me know what you think.
In its current form, it's not particularly useful (except for calculating an inverse I guess) but it could be modified to add a "reference frame", for example, which would zero-out an axis at a specific frame, ...
Most of the other knobsOnly tools feel a bit overkill, all the transform/rotate/scale/... can be done directly with an axis without the need to make  new node at all.
The determinants, I guess they can be useful, but not sure what they are useful for except calculating the inverse?

**Comment by herronelou** [comment]
Went ahead and added a "ZeroAxis" node, which inverts incoming matrices at a specific frame.

**Comment by herronelou** [comment]
I'm closing this as this is getting closer to a releasable toolset.
