### ISSUE TITLE
[Feature Request] Allow custom resolution for baking transforms

### ISSUE THREAD

**Issue by melMass** [mapoga/nuke-vector-matrix#29]
Hi Mapoga,

Thanks for this amazing toolset, I've used it extensively since I discovered it.
One issue I have is that I usually disable `image_aspect` from the cards so that my stabilized views aren't distorted.

In 3D I would just pipe a square constant to the scanline bg, but having an option on bake to set resolution/aspect would be very nice.

I think it's related to #28

**Comment by herronelou** [comment]
#28 would use the resolution of the node that is being converted rather than the project resolution for setting the 'from' cornerpin, would that work for your case?

**Comment by melMass** [comment]
Sorry, I missed your reply, yes, or maybe adding a `format` knob to the conversion panel set to root (current behavior) or selected node by default! This way the automatic behavior is expected, but we can still select a custom one. What do you think?

**Comment by herronelou** [comment]
Hi @melMass , I know it's 2 years later, but if you'd like to test this it's available now.

**Comment by melMass** [comment]
Not too late! Great thanks! Closing this then!
